#!/usr/bin/env bash


prefix="package_$2"

if [[ "package_ingest_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_filebeat_volume
	fi
	
if [[ "package_ingest_ssl_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_ssl_filebeat_volume
	fi
	
