#!/usr/bin/env bash


prefix="package_ingest_kafka_$2"

if [[ "package_ingest_kafka_ingest_kafka_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_kafka_ingest_kafka_filebeat_volume
	fi
	
